# Generated by Django 5.1.3 on 2024-12-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='list_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
