# Generated by Django 5.1.4 on 2025-01-17 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='description',
            field=models.TextField(help_text='A brief farm description and you as a farmer.', validators=[django.core.validators.MinLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(error_messages={'unique': 'Seller with this name already exists. Please choose another name!'}, help_text='Farm or farmer name. ', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
