# Generated by Django 5.1.3 on 2024-11-22 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_alter_seller_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='contact_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
