# Generated by Django 5.1.3 on 2024-11-22 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_alter_seller_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(default='Addr', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='contact_phone',
            field=models.CharField(default='+35900003343', max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='photo',
            field=models.ImageField(default='photo', upload_to='sellers/'),
            preserve_default=False,
        ),
    ]
