# Generated by Django 5.1.3 on 2024-11-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0007_alter_seller_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='profile',
            new_name='account',
        ),
    ]
