# Generated by Django 5.1.3 on 2024-11-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0008_rename_profile_seller_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
