# Generated by Django 5.1.3 on 2024-11-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0009_alter_seller_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='contact_phone',
        ),
    ]
