# Generated by Django 5.1.3 on 2024-11-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0010_remove_seller_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='contact_email',
        ),
    ]
