# Generated by Django 5.1.3 on 2024-11-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0013_alter_seller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(error_messages={'unique': 'Seller with this name already exists. Please choose another name!'}, max_length=30, unique=True),
        ),
    ]
