# Generated by Django 5.1.3 on 2024-12-05 22:44

import fMarket.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0014_alter_seller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='photo',
            field=models.ImageField(upload_to='sellers/', validators=[fMarket.validators.image_size_validator]),
        ),
    ]
