# Generated by Django 5.1.4 on 2024-12-10 12:40

import fMarket.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0015_alter_seller_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(help_text='Address of the farm.', max_length=50),
        ),
        migrations.AlterField(
            model_name='seller',
            name='city',
            field=models.CharField(help_text='City or village name the farm is allocated near.', max_length=40),
        ),
        migrations.AlterField(
            model_name='seller',
            name='description',
            field=models.TextField(help_text='A brief farm description and you as a farmer.'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(error_messages={'unique': 'Seller with this name already exists. Please choose another name!'}, help_text='Farm or farmer name. ', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='photo',
            field=models.ImageField(help_text='Photo of yourself.', upload_to='sellers/', validators=[fMarket.validators.image_size_validator]),
        ),
        migrations.AlterField(
            model_name='seller',
            name='website_url',
            field=models.URLField(blank=True, help_text='Optional. Website URL including https prefix.', null=True),
        ),
    ]
