# Generated by Django 5.1.3 on 2024-11-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
