# Generated by Django 5.1.3 on 2024-11-27 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_is_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number must include the country code, without whitespaces.', max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
