# Generated by Django 5.1.3 on 2024-11-29 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Must include the country code, without whitespaces.', max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
