# Generated by Django 5.1.3 on 2024-12-04 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_stars_review_rating_alter_review_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('Negative', 'Negative'), ('Neutral', 'Neutral'), ('Positive', 'Positive')], default='Positive', max_length=8),
        ),
    ]
