# Generated by Django 5.1.3 on 2024-12-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_date_created_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(help_text='Maximum review length: 300 characters', max_length=300),
        ),
    ]
