# Generated by Django 5.1.3 on 2024-12-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(help_text='Maximum review length: 400 characters', max_length=400),
        ),
    ]
