# Generated by Django 5.1.3 on 2024-11-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_discount_alter_product_min_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Nuts', 'Nuts'), ('Canned Food', 'Canned Food'), ('Spices', 'Spices'), ('Meat Products', 'Meat Products'), ('Fish Products', 'Fish Products'), ('Cheese', 'Cheese')], default='Vegetables', max_length=20),
        ),
    ]
