# Generated by Django 5.1.3 on 2024-11-26 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_owner_alter_product_qty_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', error_messages={django.core.validators.MinLengthValidator: 'The description length must be at least 60 characters!'}, validators=[django.core.validators.MinLengthValidator(60)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(error_messages={django.core.validators.MinLengthValidator: 'The name must be at lease 3 characters long!'}, max_length=40, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
