# Generated by Django 5.1.3 on 2024-11-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Nuts', 'Nuts'), ('Canned Food', 'Canned Food'), ('Dried Food', 'Dried Food'), ('Spices', 'Spices'), ('Meat Products', 'Meat Products'), ('Fish Products', 'Fish Products'), ('Cheese', 'Cheese')], default='Vegetables', max_length=20),
        ),
    ]
