# Generated by Django 5.1.3 on 2024-11-26 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_category'),
        ('sellers', '0014_alter_seller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sellers.seller'),
            preserve_default=False,
        ),
    ]
