# Generated by Django 5.1.3 on 2024-11-26 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_owner_product_owner_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
