# Generated by Django 5.1.3 on 2024-11-29 20:31

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', error_messages={django.core.validators.MinLengthValidator: 'The description must be at least 60 characters long!'}, validators=[django.core.validators.MinLengthValidator(60)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(error_messages={django.core.validators.MinLengthValidator: 'The name must be at least 3 characters long!'}, max_length=40, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
