# Generated by Django 5.1.3 on 2024-11-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_date_created_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='photo.jpg', upload_to='products/'),
            preserve_default=False,
        ),
    ]
