# Generated by Django 5.1.3 on 2024-11-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery',
            field=models.CharField(choices=[('International Courier', 'International Courier'), ('National Courier', 'National Courier'), ('Local Pickup', 'Local Pickup')], default='Local Pickup'),
        ),
        migrations.AddField(
            model_name='product',
            name='payment',
            field=models.CharField(choices=[('Payment on Delivery', 'Payment on Delivery'), ('PayPal', 'PayPal'), ('Bank Transfer', 'Bank Transfer'), ('Other', 'Other')], default='Payment on Delivery'),
        ),
    ]
