# Generated by Django 5.1.3 on 2024-11-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_delivery_product_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Nuts', 'Nuts'), ('Canned Food', 'Canned Food'), ('Dried Food', 'Dried Food'), ('Spices', 'Spices'), ('Meat Products', 'Meat Products'), ('Fish Products', 'Fish Products'), ('Cheese', 'Cheese'), ('Mushrooms', 'Mushrooms'), ('Other', 'Other')], default='Vegetables', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery',
            field=models.CharField(choices=[('All EU by Courier', 'All EU by Courier'), ('Within Seller Country', 'Within Seller Country'), ('Local Pickup', 'Local Pickup'), ('Other - please ask', 'Other - please ask')], default='Local Pickup'),
        ),
        migrations.AlterField(
            model_name='product',
            name='payment',
            field=models.CharField(choices=[('Payment on Delivery', 'Payment on Delivery'), ('Cash on Pick-up', 'Cash on Pick-up'), ('PayPal', 'PayPal'), ('Bank Transfer', 'Bank Transfer'), ('Other', 'Other')], default='Payment on Delivery'),
        ),
    ]
