# Generated by Django 5.1.3 on 2024-12-03 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_category_alter_product_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', error_messages={django.core.validators.MinLengthValidator: 'The description must be at least 60 characters long!'}, help_text='Minimum length: 60 characters', validators=[django.core.validators.MinLengthValidator(60)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(help_text='Recommended image size - min: 800x600, max: 1600x1200', upload_to='products/'),
        ),
    ]
