# Generated by Django 5.1.3 on 2024-12-05 22:44

import fMarket.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_product_description_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(help_text='Recommended image size - min: 800x600, max: 1600x1200', upload_to='products/', validators=[fMarket.validators.image_size_validator]),
        ),
    ]
